package com.epion_t3.targetapp.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TodoModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.title
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.description
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.due
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date due;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.actual_start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date actualStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.actual_end
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date actualEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.status
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.priority
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.tags
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.version
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.create_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.update_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.title
     *
     * @return the value of todo.title
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.title
     *
     * @param title the value for todo.title
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.description
     *
     * @return the value of todo.description
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.description
     *
     * @param description the value for todo.description
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.start
     *
     * @return the value of todo.start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withStart(Date start) {
        this.setStart(start);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.start
     *
     * @param start the value for todo.start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.due
     *
     * @return the value of todo.due
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getDue() {
        return due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withDue(Date due) {
        this.setDue(due);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.due
     *
     * @param due the value for todo.due
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setDue(Date due) {
        this.due = due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.actual_start
     *
     * @return the value of todo.actual_start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getActualStart() {
        return actualStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withActualStart(Date actualStart) {
        this.setActualStart(actualStart);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.actual_start
     *
     * @param actualStart the value for todo.actual_start
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setActualStart(Date actualStart) {
        this.actualStart = actualStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.actual_end
     *
     * @return the value of todo.actual_end
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getActualEnd() {
        return actualEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withActualEnd(Date actualEnd) {
        this.setActualEnd(actualEnd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.actual_end
     *
     * @param actualEnd the value for todo.actual_end
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setActualEnd(Date actualEnd) {
        this.actualEnd = actualEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.status
     *
     * @return the value of todo.status
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.status
     *
     * @param status the value for todo.status
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.priority
     *
     * @return the value of todo.priority
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.priority
     *
     * @param priority the value for todo.priority
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.tags
     *
     * @return the value of todo.tags
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withTags(String tags) {
        this.setTags(tags);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.tags
     *
     * @param tags the value for todo.tags
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.version
     *
     * @return the value of todo.version
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withVersion(Integer version) {
        this.setVersion(version);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.version
     *
     * @param version the value for todo.version
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.create_date
     *
     * @return the value of todo.create_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withCreateDate(Date createDate) {
        this.setCreateDate(createDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.create_date
     *
     * @param createDate the value for todo.create_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.update_date
     *
     * @return the value of todo.update_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public TodoModel withUpdateDate(Date updateDate) {
        this.setUpdateDate(updateDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.update_date
     *
     * @param updateDate the value for todo.update_date
     *
     * @mbg.generated Wed Aug 05 00:52:59 JST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}