swagger: "3.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v1"
tags:
  - name: "stub"
paths:
  /stub:
    get:
      tags:
        - "stub"
      summary: "RestApi"
      description: "RestApi"
      operationId: "getUserData"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: "id"
          required: true
          type: "integer"
      responses:
        200:
          description: "成功"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                description: "氏名"
              sex:
                type: "string"
                description: "性別"
              height:
                type: "integer"
                description: "身長(cm)"
              weight:
                type: "integer"
                description: "体重(kg)"
        400:
          description: "エラー"
        500:
          description: "エラー"