version: "3"
services:
  mysql:
    build: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  springboot:
    image: localhost:5000/epion-t3-targetapp-rest:1.0.0
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
