version: "3"
services:
  mysql:
    build: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  springboot:
    ports:
      - "8080:8080"
    links:
      - mysql
      - stub
    depends_on:
      - mysql
      - stub
    restart: always
  stub:
    build: stub
    ports:
      - "8081:8080"
    restart: always
