package com.zomu.t.epion.tropic.test.tool.epiont3targetapprest.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TodoModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.title
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.description
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.start
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.due
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Date due;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.actualStart
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Date actualstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.actualEnd
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Date actualend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.status
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.priority
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.tags
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.title
     *
     * @return the value of todo.title
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.title
     *
     * @param title the value for todo.title
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.description
     *
     * @return the value of todo.description
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.description
     *
     * @param description the value for todo.description
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.start
     *
     * @return the value of todo.start
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withStart(Date start) {
        this.setStart(start);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.start
     *
     * @param start the value for todo.start
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.due
     *
     * @return the value of todo.due
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Date getDue() {
        return due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withDue(Date due) {
        this.setDue(due);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.due
     *
     * @param due the value for todo.due
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setDue(Date due) {
        this.due = due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.actualStart
     *
     * @return the value of todo.actualStart
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Date getActualstart() {
        return actualstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withActualstart(Date actualstart) {
        this.setActualstart(actualstart);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.actualStart
     *
     * @param actualstart the value for todo.actualStart
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setActualstart(Date actualstart) {
        this.actualstart = actualstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.actualEnd
     *
     * @return the value of todo.actualEnd
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Date getActualend() {
        return actualend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withActualend(Date actualend) {
        this.setActualend(actualend);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.actualEnd
     *
     * @param actualend the value for todo.actualEnd
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setActualend(Date actualend) {
        this.actualend = actualend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.status
     *
     * @return the value of todo.status
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.status
     *
     * @param status the value for todo.status
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.priority
     *
     * @return the value of todo.priority
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.priority
     *
     * @param priority the value for todo.priority
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.tags
     *
     * @return the value of todo.tags
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public TodoModel withTags(String tags) {
        this.setTags(tags);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.tags
     *
     * @param tags the value for todo.tags
     *
     * @mbg.generated Mon Mar 04 14:34:43 JST 2019
     */
    public void setTags(String tags) {
        this.tags = tags;
    }
}