-- MySQL Script generated by MySQL Workbench
-- Sat Mar  9 09:35:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `tododb`.`todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tododb`.`todo` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `start` TIMESTAMP NULL,
  `due` TIMESTAMP NULL,
  `actual_start` TIMESTAMP NULL,
  `actual_end` TIMESTAMP NULL,
  `status` INT NULL,
  `priority` INT NULL,
  `tags` VARCHAR(300) NULL,
  `version` INT NULL,
  `create_date` TIMESTAMP NULL,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
