name: epion-t3-targetapp-rest-publish

on:
  push:
    branches:
      - 'master'
      - 'release'
      - 'demo'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          graldlw clean build docker
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: epiontropictesttool/epion-t3-targetapp-rest
          tag: 1.0.0
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}